#!/usr/bin/env bash
# This script installs Nginx and configures a custom 404 error page

apt-get update -y
apt-get install nginx -y
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
CONFIG_FILE="/etc/nginx/sites-available/default"
sed -i "/server_name _;/a \\    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        internal;\n    }" $CONFIG_FILE
service nginx restart
exit $?

