#!/usr/bin/env bash
# This script installs and configures HAProxy to distribute traffic between web-01 and web-02 using the roundrobin algorithm.

apt-get update -y
apt-get install haproxy -y

HA_CONFIG_FILE="/etc/haproxy/haproxy.cfg"

cp $HA_CONFIG_FILE ${HA_CONFIG_FILE}.bak

cat <<EOL > $HA_CONFIG_FILE
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private
    ssl-default-bind-ciphers PROFILE=SYSTEM
    ssl-default-bind-options no-sslv3

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 54.208.56.4:80 check
    server web02 35.153.57.78:80 check

listen stats
    bind *:8080
    stats enable
    stats uri /stats
    stats hide-version
    stats auth admin:admin
EOL
service haproxy restart
exit $?
