#!/usr/bin/env bash
# Indefinitely writes I am alive! to the file /tmp/my_process
# In between every I am alive! message, the program should pause for 2 seconds

PID_FILE="/var/run/my_process.pid"

start() {
    if [ -e "$PID_FILE" ]; then
        echo "manage_my_process is already running"
        exit 1
    fi

    /path/to/manage_my_process &
    echo $! > "$PID_FILE"
    echo "manage_my_process started"
}

stop() {
    if [ ! -e "$PID_FILE" ]; then
        echo "manage_my_process is not running"
        exit 1
    fi

    kill $(cat "$PID_FILE")
    rm "$PID_FILE"
    echo "manage_my_process stopped"
}

restart() {
    stop
    start
    echo "manage_my_process restarted"
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac
