#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd,
# using the while loop + IFS

while IFS=: read -r username _ user_id _ _ home_directory shell; do
    echo "The user $username is part of the $user_id gang, lives in $home_directory and rides $shell. $user_id's place is protected by the passcode x, more info about the user here: $username"
done < /etc/passwd
