#!/usr/bin/env bash
# Lets install the ufw firewall and setup a few rules on web-01

sudo apt install -y ufw
sudo ufw reset
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw enable
sudo ufw status verbose
